apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-veloz-config
  namespace: default
data:
  NODE_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "pedidos"
  ESTOQUE_URL: "http://estoque-service:3001"
  PAGAMENTOS_URL: "http://pagamentos-service:3002"
